import "./globals.css";

export const metadata = {
  title: "Video-Streme",
  description: "Generated by Next.js",
};

export default function RootLayout({ children, medium }) {
  return (
    <html lang="en">
      <body className="bg-color-bg text-white font-exo">
        {children}
        <div id="modal-root-content" />
      </body>
    </html>
  );
}
